language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean source:jar deploy --settings travis_settings.xml

# travis encrypt -r bootique/bootique-kafka-client "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique-kafka-client "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "UBFTOqDv61K++n8L4V2G8lKfluy4feh0OZL+LNdH67vUmyddXpLPknr20xuZYMvjpJfNk/39UdUDgb2tbsy5Df6usPWc3OmzEwx4hVA2413EVI59Kq9hB1+Kxv18Cr5yMcOeCKoqCBdUlHfzI5ikRnWMVb9WoiyipS0Bnk51Qeuu/X3oKFIinYpTFqyoMZjju3DmfffBrZXI1dpENV9IGXy1FVSAxkA+fWCcndO0cFJKlFbMrkMIf+6tMlB5zt7tJxKmJqEBoz0zell7pfud1hao/1TOGPaxfkRfZhOGRQQ0iMnD9qkzGImysKmKdnXxP8fJznSJKwU+nmtQqMEhbI2QfEYtnEWNcBZCE1qqESDeYiwzebvExxIIA6Y7EmAMzbLGwxLvFZoBjB3JpUpK4XjAk55QB9gKeuMzXcf3CGUM+eHoo59pRpoAN93dAt99DX7jpXvmlgPEeGibpTL2Zi1Ku/mWKN2ZCkS77uZ9wLF6MdqnIkl8nWdSE29r9Fp8mzx5lT+JcNeQGSwogrpHJxXI74BJ7J+fxkisdpn6w6kmj6qYmBcIjfEYYNVjyzAxpuKptJXnomd+LCx8WyBfYO5iFv64Aw1K9wbqM+NdwnflYTj3Qts2J82jLcrv+LJPO5NLByRSL0fey+09SRb8oxU5mvukwO58OA7vrRLP8Os="
    - secure: "jtanc8mTZnim3cfxPQ4E/PHca6OUVTexlD3linOggvlTwFq4peGbVBcwRkA5D67PdSa57dOLbQkwnCiC9TiKZx67QWlC/mmtr30EpCVbkTWRIXFoC1TvgOauDW34Xgd0g08xxCpmRmOyYMWahVnkWGbI/nAPOvaeXjkvy9danzx91WVETin/haHeDheuzLzZLZbxrHpXHnj9NiqcRRWEdvvvrH+xoIyYNTrDVGMzJMvQKGsSwJGdLrpZt17g0g92g+O10E79Y8QBCDWH3T6ZV4lgvn7AnpwACuc7TOXrM2dtOylWpV0UFnOHAQpghDKG6mrsNss1MzD7YYRwKAJBx1b2WCMEMkbAwUKYLv7k/WNLDcUXNkdlpXluXw3U6aMNWSfBrE4vIm8ofXYad2Y8Feu1RdRg6hOGs9AKglbnFay0yiavYahtTFrmjzIqpW8uymyUh7m9T/765BuSi4Zs2gYVbBU15iE4hkLjZHIoaL+m6CRyYklTdGyTSq8Qb0tMNRcde5GS5fxDEoyaXFNUBGXBfIG5G2V8rXVgVRjIvLunvu/V7WZ6dKDyRLrEALoI3F9PSPRR5xDh3/sNMldGglYJJSMMzR0uCqZ+6admQU7A14ln4LeLxsbrIjjJDPFeU5zIJxnBM+5WsJTFvCINTNq2M4VDeKoXeLbgo5IqDUo="

